### PR TITLE
ISDK-2147: Add iOS 12.0 compatibility notice.

### PR DESCRIPTION
**Pull request by ceaglest**
Please note that the KB link is not final.

### CODE REVIEW

**Review by ktoraskartwilio — COMMENTED** [review]
Suggest adding a short sentence on the root cause which is - "WebRTC class conflict issues."

**Comment by ceaglest** [comment]
Okay, I can update it. Lets make sure we agree on this before going through the rest of the open PRs.

**Comment by ceaglest** [comment]
@ktoraskartwilio, I gave it another shot. This might be a bit verbose, but let me know.

**Comment by ceaglest** [comment]
I'm closing this PR based upon findings that iOS 12.0-beta5 no longer has runtime symbol conflicts with `RTC` classes.

**Pull request closed without merging**
